"""add target_run_businesses

Revision ID: 108df6a403d2
Revises: 8b989868e314
Create Date: 2026-09-13 11:11:52.937422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '108df6a403d2'
down_revision: Union[str, Sequence[str], None] = '8b989868e314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_run_businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_run_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('crawl_status', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("crawl_status IN ('ok', 'partial', 'unreachable', 'no_website')", name='ck_target_run_businesses_crawl_status'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_run_id'], ['target_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_run_id', 'business_id', name='uq_target_run_businesses_run_business')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_run_businesses')
    # ### end Alembic commands ###
