"""add mailbox last_send_error tracking

Revision ID: 7a0fe0a19027
Revises: 108df6a403d2
Create Date: 2026-09-13 15:41:53.610700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0fe0a19027'
down_revision: Union[str, Sequence[str], None] = '108df6a403d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailboxes', sa.Column('last_send_error', sa.String(), nullable=True))
    op.add_column('mailboxes', sa.Column('last_send_error_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailboxes', 'last_send_error_at')
    op.drop_column('mailboxes', 'last_send_error')
    # ### end Alembic commands ###
