"""initial schema

Revision ID: 8b989868e314
Revises: 
Create Date: 2026-09-12 13:46:38.260840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b989868e314'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('normalized_domain', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_raw_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('overpass', 'places', 'csv')", name='ck_businesses_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_businesses_source_source_id')
    )
    op.create_index('uq_businesses_normalized_domain', 'businesses', ['normalized_domain'], unique=True, postgresql_where=sa.text('normalized_domain IS NOT NULL'))
    op.create_table('mailboxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('oauth_refresh_token_encrypted', sa.String(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('email', 'domain')", name='ck_suppressions_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'value', name='uq_suppressions_scope_value')
    )
    op.create_table('target_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_name', sa.String(), nullable=False),
    sa.Column('profile_hash', sa.String(), nullable=False),
    sa.Column('profile_yaml', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('businesses_found', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_target_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_run_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_run_id'], ['target_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_generic', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('legal_basis', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('website', 'osm')", name='ck_contacts_source'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email', name='uq_contacts_business_email')
    )
    op.create_table('crawl_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('html', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'url', name='uq_crawl_cache_business_url')
    )
    op.create_table('enrichment_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'key', name='uq_signals_business_key')
    )
    op.create_table('campaign_mailboxes',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('campaign_id', 'mailbox_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'approved', 'sent', 'bounced', 'replied', 'rejected')", name='ck_messages_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_messages_campaign_contact')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('campaign_mailboxes')
    op.drop_table('enrichment_signals')
    op.drop_table('crawl_cache')
    op.drop_table('contacts')
    op.drop_table('campaigns')
    op.drop_table('target_runs')
    op.drop_table('suppressions')
    op.drop_table('mailboxes')
    op.drop_index('uq_businesses_normalized_domain', table_name='businesses', postgresql_where=sa.text('normalized_domain IS NOT NULL'))
    op.drop_table('businesses')
    # ### end Alembic commands ###
